apiVersion: apps/v1
kind: Deployment

metadata:
  name: upload-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: upload-service

  template:
    metadata:
      labels:
        app: upload-service

    spec:
      containers:
      - name: upload-service

        image: saugat0082/upload-service:038125464adc0e7413fa0b417abea93865c48eda

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ConnectionStrings__DefaultConnection
          value: Host=postgres-service;Port=5432;Database=cv_reviewer;Username=user;Password=password