apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-analyzer-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-analyzer-service

  template:
    metadata:
      labels:
        app: ai-analyzer-service

    spec:
      containers:
      - name: ai-analyzer-service

        image: saugat0082/ai-analyzer:2.6

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: ConnectionStrings__DefaultConnection
          value: Host=postgres-service;Port=5432;Database=cv_reviewer;Username=user;Password=password